MACRO(INITIALIZE_DEPENDENCY name)
  FIND_PACKAGE(${name} QUIET)
  IF("${name}_FOUND")
    MESSAGE("Found system package for ${name}")
  ELSE()
    IF(TARGET ${name})
      MESSAGE("Found inherited target ${name}")
    ELSE()
      MESSAGE("Initializing ${name} in git submodule")
      EXECUTE_PROCESS(COMMAND "git submodule update --init -- \"external/${name}\""
                      WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
      ADD_SUBDIRECTORY("${CMAKE_CURRENT_SOURCE_DIR}/external/${name}" EXCLUDE_FROM_ALL)
    ENDIF()  
  ENDIF()
ENDMACRO()